// <auto-generated />
using System;
using AVControl.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVControl.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AVControl.Core.Entities.ChannelList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("InputSourceId")
                        .HasColumnType("int");

                    b.Property<string>("KanalAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KanalNumarasi")
                        .HasColumnType("int");

                    b.Property<bool>("KullanicidaGosterilsinMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InputSourceId");

                    b.ToTable("ChannelLists");
                });

            modelBuilder.Entity("AVControl.Core.Entities.FavoriLig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LigAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FavoriLigler");
                });

            modelBuilder.Entity("AVControl.Core.Entities.FavoriTakim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TakimAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FavoriTakimlar");
                });

            modelBuilder.Entity("AVControl.Core.Entities.InputSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InputName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IrTransmitterId")
                        .HasColumnType("int");

                    b.Property<bool>("KanalKontrolVarMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MatrixDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PortNumarasi")
                        .HasColumnType("int");

                    b.Property<int?>("RemoteControlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IrTransmitterId");

                    b.HasIndex("MatrixDeviceId");

                    b.HasIndex("RemoteControlId");

                    b.ToTable("InputSources");
                });

            modelBuilder.Entity("AVControl.Core.Entities.IrTransmitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CihazGorselUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MacAdresi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IrTransmitters");
                });

            modelBuilder.Entity("AVControl.Core.Entities.IslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Detaylar")
                        .HasColumnType("longtext");

                    b.Property<string>("IslemTipi")
                        .HasColumnType("longtext");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("IslemLoglari", (string)null);
                });

            modelBuilder.Entity("AVControl.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PinKodu")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sistem",
                            AktifMi = true,
                            KullaniciAdi = "IT",
                            PinKodu = 6161,
                            Rol = 1,
                            SifreHash = "$2a$11$nB8kNi06IPQiG//LeYdNqe10O54oTT9NvQ5QASZ641yBgrbT9mZlq",
                            Soyad = "Yöneticisi"
                        });
                });

            modelBuilder.Entity("AVControl.Core.Entities.LedProcessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CihazGorselUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CihazMarka")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<bool>("KullanicidaGosterilsinMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MacAdresi")
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SeriNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext");

                    b.Property<bool>("ViplexKontroluVarMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("LedProcessors");
                });

            modelBuilder.Entity("AVControl.Core.Entities.MacTakvim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Deplasman")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EvSahibi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LigAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MacTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Skor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YayinKanali")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MacTakvimler");
                });

            modelBuilder.Entity("AVControl.Core.Entities.MatrixDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CihazGorselUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("InputSayisi")
                        .HasColumnType("int");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MacAdresi")
                        .HasColumnType("longtext");

                    b.Property<int>("OutputSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TelnetPort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatrixDevices");
                });

            modelBuilder.Entity("AVControl.Core.Entities.OutputZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BolgeAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GuncelChannelListId")
                        .HasColumnType("int");

                    b.Property<int?>("GuncelInputSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("IrTransmitterId")
                        .HasColumnType("int");

                    b.Property<int?>("LedProcessorId")
                        .HasColumnType("int");

                    b.Property<int>("MatrixDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("PortKodu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RemoteControlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IrTransmitterId");

                    b.HasIndex("LedProcessorId");

                    b.HasIndex("MatrixDeviceId");

                    b.HasIndex("RemoteControlId");

                    b.ToTable("OutputZones");
                });

            modelBuilder.Entity("AVControl.Core.Entities.RemoteButton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("longtext");

                    b.Property<int>("RemoteControlId")
                        .HasColumnType("int");

                    b.Property<string>("TusKodu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RemoteControlId");

                    b.ToTable("RemoteButtons");
                });

            modelBuilder.Entity("AVControl.Core.Entities.RemoteControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CihazTipi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KumandaMarkaModel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProtokolTipi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RemoteControls");
                });

            modelBuilder.Entity("AVControl.Core.Entities.ChannelList", b =>
                {
                    b.HasOne("AVControl.Core.Entities.InputSource", "InputSource")
                        .WithMany("ChannelLists")
                        .HasForeignKey("InputSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputSource");
                });

            modelBuilder.Entity("AVControl.Core.Entities.InputSource", b =>
                {
                    b.HasOne("AVControl.Core.Entities.IrTransmitter", "IrTransmitter")
                        .WithMany("InputSources")
                        .HasForeignKey("IrTransmitterId");

                    b.HasOne("AVControl.Core.Entities.MatrixDevice", "MatrixDevice")
                        .WithMany("InputSources")
                        .HasForeignKey("MatrixDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVControl.Core.Entities.RemoteControl", "RemoteControl")
                        .WithMany("InputSources")
                        .HasForeignKey("RemoteControlId");

                    b.Navigation("IrTransmitter");

                    b.Navigation("MatrixDevice");

                    b.Navigation("RemoteControl");
                });

            modelBuilder.Entity("AVControl.Core.Entities.IslemLog", b =>
                {
                    b.HasOne("AVControl.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("IslemLoglari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AVControl.Core.Entities.OutputZone", b =>
                {
                    b.HasOne("AVControl.Core.Entities.IrTransmitter", "IrTransmitter")
                        .WithMany()
                        .HasForeignKey("IrTransmitterId");

                    b.HasOne("AVControl.Core.Entities.LedProcessor", "LedProcessor")
                        .WithMany("OutputZones")
                        .HasForeignKey("LedProcessorId");

                    b.HasOne("AVControl.Core.Entities.MatrixDevice", "MatrixDevice")
                        .WithMany("OutputZones")
                        .HasForeignKey("MatrixDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVControl.Core.Entities.RemoteControl", "RemoteControl")
                        .WithMany()
                        .HasForeignKey("RemoteControlId");

                    b.Navigation("IrTransmitter");

                    b.Navigation("LedProcessor");

                    b.Navigation("MatrixDevice");

                    b.Navigation("RemoteControl");
                });

            modelBuilder.Entity("AVControl.Core.Entities.RemoteButton", b =>
                {
                    b.HasOne("AVControl.Core.Entities.RemoteControl", "RemoteControl")
                        .WithMany("RemoteButtons")
                        .HasForeignKey("RemoteControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemoteControl");
                });

            modelBuilder.Entity("AVControl.Core.Entities.InputSource", b =>
                {
                    b.Navigation("ChannelLists");
                });

            modelBuilder.Entity("AVControl.Core.Entities.IrTransmitter", b =>
                {
                    b.Navigation("InputSources");
                });

            modelBuilder.Entity("AVControl.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("IslemLoglari");
                });

            modelBuilder.Entity("AVControl.Core.Entities.LedProcessor", b =>
                {
                    b.Navigation("OutputZones");
                });

            modelBuilder.Entity("AVControl.Core.Entities.MatrixDevice", b =>
                {
                    b.Navigation("InputSources");

                    b.Navigation("OutputZones");
                });

            modelBuilder.Entity("AVControl.Core.Entities.RemoteControl", b =>
                {
                    b.Navigation("InputSources");

                    b.Navigation("RemoteButtons");
                });
#pragma warning restore 612, 618
        }
    }
}
